@echo off
echo 🤖 CONFIGURANDO ORCABOT DEEPSEEK
echo.

:: 🔐 ENCRIPTACIÓN
set ENCRYPTION_PASSWORD=ENCRYPTION_PASSWORD
set ENCRYPTION_SALT=ENCRYPTION_SALT
set ENCRYPTION_ITERATIONS=480000

:: 🏦 WALLET
set PHANTOM_PRIVATE_KEY_BYTES=PHANTOM_PRIVATE_KEY_BYTES
set PHANTOM_WALLET=PHANTOM_WALLET
set PHANTOM_PUBLIC_KEY=PHANTOM_WALLET

:: 🌐 HELIUS RPC
set HELIUS_VOICEINDIGO_API_KEY=HELIUS_VOICEINDIGO_API_KEY

:: 🤖 TELEGRAM
set TELEGRAM_BOT_TOKEN=TELEGRAM_BOT_TOKEN
set TELEGRAM_CHAT_ID=TELEGRAM_CHAT_ID

:: 💰 TRADING (valores por defecto)
set INITIAL_CAPITAL_USD=1000
set MIN_USDC_BALANCE=10
set MIN_SOL_FEES=0.05
set POSITION_SIZE_PERCENT=0.10
set MAX_CONCURRENT_TRADES=5

:: 🎯 RIESGO
set STOP_LOSS_PERCENT=2.0
set TAKE_PROFIT_PERCENT=5.0
set DAILY_LOSS_LIMIT_PERCENT=2.0
set MAX_DRAWDOWN_PERCENT=15.0

:: 🧠 ML
set ML_CONFIDENCE_THRESHOLD=0.65
set TRAINING_INTERVAL_HOURS=12

echo ✅ Variables configuradas!
echo.
echo 📋 Para verificar: python config.py
echo 🚀 Para ejecutar bot: python run_bot_simple.py
echo.
pause
